import { Movie, Genre, Country } from "@/types/movie";

export const MOCK_GENRES: Genre[] = [
  { id: "g1", name: "Hành động", slug: "hanh-dong", description: "Những pha rượt đuổi gay cấn và chiến đấu mãn nhãn", count: 18 },
  { id: "g2", name: "Viễn tưởng", slug: "vien-tuong", description: "Khám phá tương lai, không gian và công nghệ vượt bậc", count: 14 },
  { id: "g3", name: "Tình cảm", slug: "tinh-cam", description: "Những câu chuyện tình yêu sâu lắng và lãng mạn", count: 16 },
  { id: "g4", name: "Hoạt hình", slug: "hoat-hinh", description: "Thế giới anime và hoạt họa đa màu sắc cho mọi lứa tuổi", count: 12 },
  { id: "g5", name: "Kinh dị", slug: "kinh-di", description: "Rùng rợn, giật gân và ám ảnh tâm lý", count: 10 },
  { id: "g6", name: "Tâm lý", slug: "tam-ly", description: "Khám phá chiều sâu nội tâm và số phận con người", count: 15 },
  { id: "g7", name: "Hài hước", slug: "hai-huoc", description: "Mang lại tiếng cười sảng khoái và thư giãn", count: 9 },
  { id: "g8", name: "Phiêu lưu", slug: "phieu-luu", description: "Những cuộc hành trình kỳ thú khám phá vùng đất mới", count: 11 },
  { id: "g9", name: "Tội phạm", slug: "toi-pham", description: "Mưu đồ đen tối, điều tra phá án hồi hộp", count: 8 },
];

export const MOCK_COUNTRIES: Country[] = [
  { id: "c1", name: "Âu Mỹ", slug: "au-my", code: "US", count: 25 },
  { id: "c2", name: "Hàn Quốc", slug: "han-quoc", code: "KR", count: 20 },
  { id: "c3", name: "Nhật Bản", slug: "nhat-ban", code: "JP", count: 15 },
  { id: "c4", name: "Trung Quốc", slug: "trung-quoc", code: "CN", count: 14 },
  { id: "c5", name: "Việt Nam", slug: "viet-nam", code: "VN", count: 8 },
  { id: "c6", name: "Anh Quốc", slug: "anh-quoc", code: "GB", count: 10 },
];

const DEMO_SOURCES = [
  {
    serverName: "VIP FastCDN #1",
    label: "4K Ultra HD (Tốc độ cao)",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    type: "mp4" as const,
  },
  {
    serverName: "VIP Backup #2",
    label: "1080p FHD (Ổn định)",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    type: "mp4" as const,
  },
  {
    serverName: "Hydra Stream #3",
    label: "720p HD (Tiết kiệm data)",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    type: "mp4" as const,
  },
];

export const MOCK_MOVIES: Movie[] = [
  {
    id: "m1",
    slug: "dune-part-two",
    title: "Dune: Hành Tinh Cát - Phần 2",
    originalTitle: "Dune: Part Two",
    description: "Paul Atreides hợp nhất với Chani và người Fremen trên con đường tìm kiếm sự trả thù cho gia tộc của mình, đồng thời đối mặt với lựa chọn giữa tình yêu của cuộc đời và số phận của vũ trụ.",
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1920&auto=format&fit=crop&q=80",
    year: 2024,
    rating: 8.8,
    duration: "166 phút",
    country: "Âu Mỹ",
    countrySlug: "au-my",
    genres: ["Hành động", "Viễn tưởng", "Phiêu lưu"],
    genreSlugs: ["hanh-dong", "vien-tuong", "phieu-luu"],
    quality: "4K Ultra HD",
    language: "Vietsub + Thuyết minh",
    type: "single",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem", "Austin Butler"],
    isHot: true,
    isLatest: true,
    isRecommended: true,
    views: 1250000,
    episodes: [
      {
        id: "e1-1",
        name: "Full Movie",
        slug: "full",
        episodeNumber: 1,
        seasonNumber: 1,
        duration: "166 phút",
        videoSources: DEMO_SOURCES,
      },
    ],
  },
  {
    id: "m2",
    slug: "oppenheimer",
    title: "Oppenheimer",
    originalTitle: "Oppenheimer",
    description: "Câu chuyện lịch sử đầy kịch tính về cuộc đời của nhà vật lý lý thuyết J. Robert Oppenheimer, người đóng vai trò tối quan trọng trong Dự án Manhattan khai sinh ra quả bom nguyên tử đầu tiên.",
    posterUrl: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1920&auto=format&fit=crop&q=80",
    year: 2023,
    rating: 8.9,
    duration: "180 phút",
    country: "Âu Mỹ",
    countrySlug: "au-my",
    genres: ["Tâm lý", "Tội phạm"],
    genreSlugs: ["tam-ly", "toi-pham"],
    quality: "4K HDR",
    language: "Vietsub",
    type: "single",
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    isHot: true,
    isLatest: false,
    isRecommended: true,
    views: 980000,
    episodes: [
      {
        id: "e2-1",
        name: "Full Movie",
        slug: "full",
        episodeNumber: 1,
        seasonNumber: 1,
        duration: "180 phút",
        videoSources: DEMO_SOURCES,
      },
    ],
  },
  {
    id: "m3",
    slug: "shogun-2024",
    title: "Tướng Quân: Shogun",
    originalTitle: "Shōgun (Season 1)",
    description: "Bối cảnh nước Nhật phong kiến năm 1600 đầy biến động khi Lãnh chúa Toranaga đấu tranh vì mạng sống trước liên minh các đối thủ quyền lực tại Hội đồng Nhiếp chính.",
    posterUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1920&auto=format&fit=crop&q=80",
    year: 2024,
    rating: 9.1,
    duration: "60 phút/tập",
    country: "Âu Mỹ",
    countrySlug: "au-my",
    genres: ["Hành động", "Tâm lý", "Phiêu lưu"],
    genreSlugs: ["hanh-dong", "tam-ly", "phieu-luu"],
    quality: "4K UHD",
    language: "Vietsub + Lồng tiếng",
    type: "series",
    director: "Rachel Kondo, Justin Marks",
    cast: ["Hiroyuki Sanada", "Cosmo Jarvis", "Anna Sawai", "Tadanobu Asano"],
    totalEpisodes: 10,
    currentEpisode: "Tập 10/10",
    isHot: true,
    isLatest: true,
    isRecommended: true,
    views: 2400000,
    episodes: Array.from({ length: 10 }, (_, i) => ({
      id: `e3-${i + 1}`,
      name: `Tập ${i + 1}: ${
        ["Anjin", "Kẻ tôi tớ của hai chủ", "Ngày mai là ngày mai", "Hàng rào thứ tám", "Phá vỡ giới hạn", "Mưa đỏ", "Chiếc gậy hoa sen", "Màn sương đen", "Lời thú tội màu đỏ tươi", "Giấc mơ của một giấc mơ"][i]
      }`,
      slug: `tap-${i + 1}`,
      episodeNumber: i + 1,
      seasonNumber: 1,
      duration: "58 phút",
      videoSources: DEMO_SOURCES,
    })),
  },
  {
    id: "m4",
    slug: "queen-of-tears",
    title: "Nữ Hoàng Nước Mắt",
    originalTitle: "Queen of Tears",
    description: "Cuộc khủng hoảng và sự hồi sinh kỳ diệu trong hôn nhân giữa Hong Hae-in, tiểu thư thừa kế tài phiệt thế hệ thứ 3, và Baek Hyun-woo, chàng trai tài giỏi sinh ra từ vùng nông thôn bình dị.",
    posterUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1920&auto=format&fit=crop&q=80",
    year: 2024,
    rating: 8.6,
    duration: "75 phút/tập",
    country: "Hàn Quốc",
    countrySlug: "han-quoc",
    genres: ["Tình cảm", "Tâm lý", "Hài hước"],
    genreSlugs: ["tinh-cam", "tam-ly", "hai-huoc"],
    quality: "1080p FHD",
    language: "Vietsub + Thuyết minh",
    type: "series",
    director: "Jang Young-woo, Kim Hee-won",
    cast: ["Kim Soo-hyun", "Kim Ji-won", "Park Sung-hoon", "Kwak Dong-yeon"],
    totalEpisodes: 16,
    currentEpisode: "Tập 16/16",
    isHot: true,
    isLatest: true,
    isRecommended: true,
    views: 3100000,
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: `e4-${i + 1}`,
      name: `Tập ${i + 1}`,
      slug: `tap-${i + 1}`,
      episodeNumber: i + 1,
      seasonNumber: 1,
      duration: "72 phút",
      videoSources: DEMO_SOURCES,
    })),
  },
  {
    id: "m5",
    slug: "cyberpunk-edgerunners",
    title: "Cyberpunk: Edgerunners",
    originalTitle: "Cyberpunk: Edgerunners",
    description: "Tại thành phố Night City của tương lai bị ám ảnh bởi công nghệ và biến đổi cơ thể, một đứa trẻ đường phố quyết tâm sống sót bằng cách trở thành Edgerunner - một lính đánh thuê ngoài vòng pháp luật.",
    posterUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1920&auto=format&fit=crop&q=80",
    year: 2023,
    rating: 9.0,
    duration: "25 phút/tập",
    country: "Nhật Bản",
    countrySlug: "nhat-ban",
    genres: ["Hoạt hình", "Hành động", "Viễn tưởng"],
    genreSlugs: ["hoat-hinh", "hanh-dong", "vien-tuong"],
    quality: "4K UHD",
    language: "Vietsub + Lồng tiếng",
    type: "series",
    director: "Hiroyuki Imaishi",
    cast: ["KENN", "Aoi Yuuki", "Hiroki Touchi", "Michiko Kaiden"],
    totalEpisodes: 10,
    currentEpisode: "Tập 10/10",
    isHot: false,
    isLatest: false,
    isRecommended: true,
    views: 1850000,
    episodes: Array.from({ length: 10 }, (_, i) => ({
      id: `e5-${i + 1}`,
      name: `Tập ${i + 1}`,
      slug: `tap-${i + 1}`,
      episodeNumber: i + 1,
      seasonNumber: 1,
      duration: "25 phút",
      videoSources: DEMO_SOURCES,
    })),
  },
  {
    id: "m6",
    slug: "interstellar",
    title: "Hố Đen Tử Thần",
    originalTitle: "Interstellar",
    description: "Khi Trái Đất dần cạn kiệt sự sống, một nhóm nhà thám hiểm dấn thân vào chuyến du hành liên thiên hà qua một lỗ sâu không gian để tìm kiếm ngôi nhà mới cho nhân loại.",
    posterUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1920&auto=format&fit=crop&q=80",
    year: 2014,
    rating: 8.7,
    duration: "169 phút",
    country: "Âu Mỹ",
    countrySlug: "au-my",
    genres: ["Viễn tưởng", "Tâm lý", "Phiêu lưu"],
    genreSlugs: ["vien-tuong", "tam-ly", "phieu-luu"],
    quality: "4K IMAX",
    language: "Vietsub + Thuyết minh",
    type: "single",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    isHot: false,
    isLatest: false,
    isRecommended: true,
    views: 3800000,
    episodes: [
      {
        id: "e6-1",
        name: "Full Movie",
        slug: "full",
        episodeNumber: 1,
        seasonNumber: 1,
        duration: "169 phút",
        videoSources: DEMO_SOURCES,
      },
    ],
  },
  {
    id: "m7",
    slug: "mai-2024",
    title: "Mai",
    originalTitle: "Mai",
    description: "Mai, một phụ nữ làm nghề massage gần 40 tuổi với số phận nhiều biến cố, ngỡ như tìm thấy hạnh phúc bên Dương - chàng nhạc công trẻ tuổi đào hoa. Nhưng áp lực gia đình và định kiến xã hội đẩy họ vào ngã rẽ.",
    posterUrl: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=1920&auto=format&fit=crop&q=80",
    year: 2024,
    rating: 8.2,
    duration: "131 phút",
    country: "Việt Nam",
    countrySlug: "viet-nam",
    genres: ["Tâm lý", "Tình cảm"],
    genreSlugs: ["tam-ly", "tinh-cam"],
    quality: "1080p FHD",
    language: "Tiếng Việt gốc",
    type: "single",
    director: "Trấn Thành",
    cast: ["Phương Anh Đào", "Tuấn Trần", "Hồng Đào", "Trấn Thành"],
    isHot: true,
    isLatest: true,
    isRecommended: true,
    views: 4200000,
    episodes: [
      {
        id: "e7-1",
        name: "Full Movie",
        slug: "full",
        episodeNumber: 1,
        seasonNumber: 1,
        duration: "131 phút",
        videoSources: DEMO_SOURCES,
      },
    ],
  },
  {
    id: "m8",
    slug: "suzume-no-tojimari",
    title: "Khóa Chặt Cửa Nào Suzume",
    originalTitle: "Suzume no Tojimari",
    description: "Cô nữ sinh 17 tuổi Suzume gặp gỡ chàng trai trẻ Souta đang trên hành trình tìm kiếm những cánh cửa huyền bí. Khi những thảm họa dần mở ra khắp Nhật Bản, Suzume phải đóng chặt các cánh cửa cứu lấy thế giới.",
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920&auto=format&fit=crop&q=80",
    year: 2023,
    rating: 8.5,
    duration: "121 phút",
    country: "Nhật Bản",
    countrySlug: "nhat-ban",
    genres: ["Hoạt hình", "Phiêu lưu", "Tình cảm"],
    genreSlugs: ["hoat-hinh", "phieu-luu", "tinh-cam"],
    quality: "4K UHD",
    language: "Vietsub + Lồng tiếng",
    type: "single",
    director: "Makoto Shinkai",
    cast: ["Nanoka Hara", "Hokuto Matsumura", "Eri Fukatsu"],
    isHot: false,
    isLatest: false,
    isRecommended: true,
    views: 1670000,
    episodes: [
      {
        id: "e8-1",
        name: "Full Movie",
        slug: "full",
        episodeNumber: 1,
        seasonNumber: 1,
        duration: "121 phút",
        videoSources: DEMO_SOURCES,
      },
    ],
  },
  {
    id: "m9",
    slug: "john-wick-chapter-4",
    title: "Sát Thủ John Wick: Chương 4",
    originalTitle: "John Wick: Chapter 4",
    description: "John Wick tìm ra con đường để đánh bại Hội Tối Cao. Nhưng trước khi giành lại tự do, anh phải đối mặt với kẻ thù mới có liên minh hùng mạnh trên toàn cầu và biến những người bạn cũ thành kẻ địch.",
    posterUrl: "https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1920&auto=format&fit=crop&q=80",
    year: 2023,
    rating: 8.7,
    duration: "169 phút",
    country: "Âu Mỹ",
    countrySlug: "au-my",
    genres: ["Hành động", "Tội phạm"],
    genreSlugs: ["hanh-dong", "toi-pham"],
    quality: "4K HDR",
    language: "Vietsub + Thuyết minh",
    type: "single",
    director: "Chad Stahelski",
    cast: ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård", "Laurence Fishburne"],
    isHot: true,
    isLatest: false,
    isRecommended: true,
    views: 2800000,
    episodes: [
      {
        id: "e9-1",
        name: "Full Movie",
        slug: "full",
        episodeNumber: 1,
        seasonNumber: 1,
        duration: "169 phút",
        videoSources: DEMO_SOURCES,
      },
    ],
  },
  {
    id: "m10",
    slug: "arcane-season-2",
    title: "Arcane: Liên Minh Huyền Thoại - Mùa 2",
    originalTitle: "Arcane: League of Legends Season 2",
    description: "Căng thẳng leo thang đỉnh điểm giữa thành phố tiên tiến Piltover và khu ổ chuột Zaun ngột ngạt khi hai chị em Vi và Jinx đứng ở hai đầu chiến tuyến.",
    posterUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1920&auto=format&fit=crop&q=80",
    year: 2024,
    rating: 9.3,
    duration: "42 phút/tập",
    country: "Âu Mỹ",
    countrySlug: "au-my",
    genres: ["Hoạt hình", "Hành động", "Viễn tưởng"],
    genreSlugs: ["hoat-hinh", "hanh-dong", "vien-tuong"],
    quality: "4K Dolby Vision",
    language: "Vietsub + Lồng tiếng",
    type: "series",
    director: "Christian Linke, Alex Yee",
    cast: ["Hailee Steinfeld", "Ella Purnell", "Katie Leung", "Kevin Alejandro"],
    totalEpisodes: 9,
    currentEpisode: "Tập 9/9",
    isHot: true,
    isLatest: true,
    isRecommended: true,
    views: 4500000,
    episodes: Array.from({ length: 9 }, (_, i) => ({
      id: `e10-${i + 1}`,
      name: `Tập ${i + 1}: ${["Nặng nợ thù xưa", "Khi bầu trời đổ máu", "Kẻ sống sót", "Đêm tăm tối", "Vết sẹo", "Tiếng súng cuối", "Giờ khắc định mệnh", "Ngọn lửa bừng cháy", "Hồi kết bi tráng"][i]}`,
      slug: `tap-${i + 1}`,
      episodeNumber: i + 1,
      seasonNumber: 2,
      duration: "42 phút",
      videoSources: DEMO_SOURCES,
    })),
  },
  {
    id: "m11",
    slug: "parasite-2019",
    title: "Ký Sinh Trùng",
    originalTitle: "Parasite (Gisaengchung)",
    description: "Gia đình Kim nghèo khó dần thâm nhập vào cuộc sống hào nhoáng của gia đình họ Park giàu có bằng những thủ đoạn tinh vi, dẫn đến bước ngoặt bi kịch không ai ngờ tới.",
    posterUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&auto=format&fit=crop&q=80",
    year: 2019,
    rating: 8.9,
    duration: "132 phút",
    country: "Hàn Quốc",
    countrySlug: "han-quoc",
    genres: ["Tâm lý", "Kinh dị", "Hài hước"],
    genreSlugs: ["tam-ly", "kinh-di", "hai-huoc"],
    quality: "4K UHD",
    language: "Vietsub + Thuyết minh",
    type: "single",
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    isHot: false,
    isLatest: false,
    isRecommended: true,
    views: 3100000,
    episodes: [
      {
        id: "e11-1",
        name: "Full Movie",
        slug: "full",
        episodeNumber: 1,
        seasonNumber: 1,
        duration: "132 phút",
        videoSources: DEMO_SOURCES,
      },
    ],
  },
  {
    id: "m12",
    slug: "three-body-problem",
    title: "Bài Toán 3 Thể",
    originalTitle: "3 Body Problem",
    description: "Một quyết định định mệnh tại Trung Quốc thập niên 1960 vang vọng xuyên không gian và thời gian đến hiện tại, buộc một nhóm các nhà khoa học lỗi lạc phải đối mặt với mối đe dọa sinh tồn lớn nhất của nhân loại.",
    posterUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&auto=format&fit=crop&q=80",
    year: 2024,
    rating: 8.1,
    duration: "55 phút/tập",
    country: "Âu Mỹ",
    countrySlug: "au-my",
    genres: ["Viễn tưởng", "Tâm lý", "Phiêu lưu"],
    genreSlugs: ["vien-tuong", "tam-ly", "phieu-luu"],
    quality: "4K HDR",
    language: "Vietsub",
    type: "series",
    director: "David Benioff, D.B. Weiss",
    cast: ["Benedict Wong", "Jess Hong", "Jovan Adepo", "Eiza González"],
    totalEpisodes: 8,
    currentEpisode: "Tập 8/8",
    isHot: true,
    isLatest: true,
    isRecommended: false,
    views: 1950000,
    episodes: Array.from({ length: 8 }, (_, i) => ({
      id: `e12-${i + 1}`,
      name: `Tập ${i + 1}`,
      slug: `tap-${i + 1}`,
      episodeNumber: i + 1,
      seasonNumber: 1,
      duration: "55 phút",
      videoSources: DEMO_SOURCES,
    })),
  },
];
